baseURL = "http://rhapsode.es"
languageCode = "es-es"
title = "Rhapsode NWN"
description = "Blog de Rhapsode donde puedes encontrar todas las herramientas, traducciones y modulos que he realizado para el juego Neverwinter Nights Enhanced Edition así como mi blog acerca de Fantasía"
theme = "hugo-fraktur"

# Ajustes de rutas para GitHub Pages
canonifyURLs = true
relativeURLs = false  # <--- CAMBIA ESTO A FALSE

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
description = "Modulos, utilidades y demás proyectos para NWN EE creados por Rhapsode"
author = "Rhapsode"
showStorageCode = true
custom_css = ["css/custom.css"]
[menu]
  [[menu.main]]
    identifier = "menu-inicio"
    pre = "<i class='fas fa-dice-d20'></i>"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "menu-blog"
    pre = "<i class='fas fa-scroll'></i>"
    name = "Blog"
    url = "/cronicas/"
    weight = 2

  [[menu.main]]
    identifier = "menu-proyectos"
    pre = "<i class='fas fa-hammer'></i>"
    name = "Proyectos"
    url = "/proyectos/"
    weight = 3

  [[menu.main]]
    identifier = "menu-utils"
    pre = "<i class='fas fa-tools'></i>"
    name = "Utilidades"
    url = "/utils/"
    weight = 4